create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke execute on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end;
$$;

create table public.agents (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null check (char_length(name) between 1 and 80),
  role text not null check (role in ('admin', 'agent')),
  active boolean not null default true,
  access_configured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.activity_definitions (
  id bigint generated by default as identity primary key,
  code text not null unique,
  label_zh text not null,
  label_en text not null,
  points integer not null check (points between 0 and 100),
  sort_order integer not null,
  active boolean not null default true
);

create table public.daily_activity (
  id bigint generated by default as identity primary key,
  agent_id bigint not null references public.agents(id) on delete cascade,
  activity_date date not null,
  completed_action_ids integer[] not null default '{}',
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (agent_id, activity_date)
);

create table public.weekly_reviews (
  id bigint generated by default as identity primary key,
  agent_id bigint not null references public.agents(id) on delete cascade,
  week_start date not null,
  strongest_action text not null default '',
  biggest_gap text not null default '',
  top_prospects text not null default '',
  next_improvement text not null default '',
  next_case_target text not null default '',
  next_tpc_target text not null default '',
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  unique (agent_id, week_start)
);

create table public.agent_credentials (
  agent_id bigint primary key references public.agents(id) on delete cascade,
  salt text not null,
  code_hash text not null,
  algorithm text not null default 'pbkdf2-sha256' check (algorithm = 'pbkdf2-sha256'),
  iterations integer not null default 120000 check (iterations between 100000 and 1000000),
  updated_at timestamptz not null default now()
);

create table public.scoreboard_login_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  agent_id bigint not null references public.agents(id) on delete cascade,
  attempted_at timestamptz not null default now()
);

create index daily_activity_agent_date_idx on public.daily_activity (agent_id, activity_date);
create index weekly_reviews_agent_week_idx on public.weekly_reviews (agent_id, week_start);
create index agents_active_role_idx on public.agents (active, role, code);
create index scoreboard_login_attempts_lookup_idx
  on public.scoreboard_login_attempts (user_id, agent_id, attempted_at desc);

create or replace function private.current_agent_id()
returns bigint
language sql
stable
set search_path = ''
as $$
  select nullif(auth.jwt() -> 'app_metadata' ->> 'scoreboard_agent_id', '')::bigint
$$;

create or replace function private.current_scoreboard_role()
returns text
language sql
stable
set search_path = ''
as $$
  select auth.jwt() -> 'app_metadata' ->> 'scoreboard_role'
$$;

create or replace function private.is_scoreboard_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select private.current_scoreboard_role()) = 'admin'
    and exists (
      select 1
      from public.agents
      where id = (select private.current_agent_id())
        and role = 'admin'
        and active
    )
$$;

create or replace function private.can_access_scoreboard_agent(target_agent_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select
    (select private.is_scoreboard_admin())
    or exists (
      select 1
      from public.agents
      where id = (select private.current_agent_id())
        and id = target_agent_id
        and role = 'agent'
        and active
        and (select private.current_scoreboard_role()) = 'agent'
    )
$$;

revoke all on function private.current_agent_id() from public;
revoke all on function private.current_scoreboard_role() from public;
revoke all on function private.is_scoreboard_admin() from public;
revoke all on function private.can_access_scoreboard_agent(bigint) from public;
grant execute on function private.current_agent_id() to authenticated;
grant execute on function private.current_scoreboard_role() to authenticated;
grant execute on function private.is_scoreboard_admin() to authenticated;
grant execute on function private.can_access_scoreboard_agent(bigint) to authenticated;

alter table public.agents enable row level security;
alter table public.activity_definitions enable row level security;
alter table public.daily_activity enable row level security;
alter table public.weekly_reviews enable row level security;
alter table public.agent_credentials enable row level security;
alter table public.scoreboard_login_attempts enable row level security;

create policy "signed in users can read the agent roster"
on public.agents for select
to authenticated
using (true);

create policy "admins can insert agents"
on public.agents for insert
to authenticated
with check ((select private.is_scoreboard_admin()));

create policy "admins can update agents"
on public.agents for update
to authenticated
using ((select private.is_scoreboard_admin()))
with check ((select private.is_scoreboard_admin()));

create policy "admins can delete agents"
on public.agents for delete
to authenticated
using ((select private.is_scoreboard_admin()));

create policy "signed in users can read active definitions"
on public.activity_definitions for select
to authenticated
using (active or (select private.is_scoreboard_admin()));

create policy "admins can manage definitions"
on public.activity_definitions for all
to authenticated
using ((select private.is_scoreboard_admin()))
with check ((select private.is_scoreboard_admin()));

create policy "users can read authorized daily activity"
on public.daily_activity for select
to authenticated
using (
  (select private.can_access_scoreboard_agent(agent_id))
);

create policy "users can insert authorized daily activity"
on public.daily_activity for insert
to authenticated
with check (
  (select private.can_access_scoreboard_agent(agent_id))
);

create policy "users can update authorized daily activity"
on public.daily_activity for update
to authenticated
using (
  (select private.can_access_scoreboard_agent(agent_id))
)
with check (
  (select private.can_access_scoreboard_agent(agent_id))
);

create policy "users can read authorized weekly reviews"
on public.weekly_reviews for select
to authenticated
using (
  (select private.can_access_scoreboard_agent(agent_id))
);

create policy "users can insert authorized weekly reviews"
on public.weekly_reviews for insert
to authenticated
with check (
  (select private.can_access_scoreboard_agent(agent_id))
);

create policy "users can update authorized weekly reviews"
on public.weekly_reviews for update
to authenticated
using (
  (select private.can_access_scoreboard_agent(agent_id))
)
with check (
  (select private.can_access_scoreboard_agent(agent_id))
);

grant usage on schema public to authenticated;
grant select on public.agents, public.activity_definitions to authenticated;
grant select, insert, update on public.daily_activity, public.weekly_reviews to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke all on public.agent_credentials from anon, authenticated;
revoke all on public.scoreboard_login_attempts from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete
on public.agents, public.agent_credentials, public.scoreboard_login_attempts
to service_role;
grant usage, select on all sequences in schema public to service_role;

insert into public.agents (id, code, name, role, active)
values
  (1, 'AD001', 'AD Serene', 'admin', true),
  (2, 'AG001', '代理 A', 'agent', true),
  (3, 'AG002', '代理 B', 'agent', true),
  (4, 'AG003', '代理 C', 'agent', true);

select setval(pg_get_serial_sequence('public.agents', 'id'), 4, true);

insert into public.activity_definitions (id, code, label_zh, label_en, points, sort_order, active)
values
  (1, 'prospects', '新增 5 位潜在客户名单', 'Add 5 new prospect names', 1, 1, true),
  (2, 'approaches', '完成 10 次电话 / WhatsApp 接触', '10 calls or WhatsApp approaches', 2, 2, true),
  (3, 'conversations', '完成 5 次有效沟通', '5 meaningful conversations', 2, 3, true),
  (4, 'appointments', '预约 2 个会面', 'Fix 2 appointments', 2, 4, true),
  (5, 'conduct', '完成 1 个会面', 'Conduct 1 appointment', 2, 5, true),
  (6, 'followup', '跟进重点潜在客户', 'Follow up hot prospects', 1, 6, true),
  (7, 'referral', '主动要求转介绍', 'Ask for a referral', 1, 7, true),
  (8, 'tomorrow', '为明天创造预约', 'Create tomorrow''s appointment', 1, 8, true);

select setval(pg_get_serial_sequence('public.activity_definitions', 'id'), 8, true);
